import Head from 'next/head'
import Image from 'next/image'

// Images
import profileImage from "../public/p2.png";
import graphicDesign from "../public/design.png";
import code from "../public/code.png";
import image1 from "../public/web1.png"
import image2 from "../public/web2.png";
import image3 from "../public/web3.png";

// framer
import { motion } from "framer-motion";


// Icons
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiOutlineGithub, AiFillLinkedin, AiOutlineInstagram} from "react-icons/ai";

// hooks
import { useState } from "react";


export default function Home() {

  // function

  const [darkmode, setdarkmode]=useState(false);
  return (
    <div className={darkmode ? "dark" : ""}>
      <Head>
        <title>Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;800&display=swap');
        </style>
      </Head>

      <main className="font-poppins bg-yellow-50 min-h-screen px-10 md:px-20 lg:px-40 dark:bg-black">
        {/*  nav and hero */}
        <section>
          {/* nav */}
          <nav className="py-10 flex justify-between">
            <h1 className="text-sm md:text-xl dark:text-white">
              Developed by Me
            </h1>
            <ul className="flex items-center">
              {/* Icon */}
              <li>
                <BsFillMoonStarsFill
                  className=" cursor-pointer text-xl mx-5 dark:text-white"
                  onClick={() => setdarkmode(!darkmode)}
                />
              </li>
              <li>
                <a
                  href="https://docs.google.com/document/d/1ncFjAgAP4ZjAWjADcuFm-qjZwstoz0hLqtH0eqgOVxI/edit?usp=sharing"
                  download={"resume"}
                  className="bg-yellow-400 text-black px-4 py-2 border-none rounded-md"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* hero */}

          <div className="text-center p-10">
            <h1 className="text-5xl font-bold text-yellow-400 md:text-6xl lg:text-7xl lg:mb-4">
              Lakshmi Anuradha
            </h1>

            <h3 className="text-2xl py-4 md:text-3xl dark:text-white">
              Frontend Developer
            </h3>
            <p className="text-sm py-4 text-gray-400 leading-6 max-w-xl mx-auto md:text-md dark:text-white">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Dignissimos impedit voluptate quod at esse tenetur atque,
              architecto culpa doloribus minus iusto necessitatibus ipsum
              corrupti accusantium ab cumque accusamus! Quaerat, saepe.
            </p>
          </div>

          {/* socials */}
          <div className="flex text-5xl justify-center gap-16 text-gray-600">
            <a href="https://github.com/bklanuradha">
              <AiOutlineGithub />
            </a>
            <a href="https://www.linkedin.com/in/lakshmi-anuradha-53b679213/">
              <AiFillLinkedin />
            </a>
            <a href="https://www.instagram.com/anuradhakankanamge/">
              <AiOutlineInstagram />
            </a>
          </div>

          {/* profile */}
          <motion.div
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5 }}
          >
            <div className="m-auto relative bg-gradient-to-b from-yellow-200 w-80 h-80 p-5 mt-20 rounded-full">
              <Image
                src={profileImage}
                alt="profile image"
                layout="fill"
                objectFit="cover"
              />
            </div>
          </motion.div>
        </section>

        {/* services */}
        <section>
          <div>
            <h2 className="text-5xl py-10 font-bold opacity-60 dark:text-white">
              Services I Offer
            </h2>
            <p className="text-sm py-2 text-gray-400 leading-6 dark:text-white">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Dignissimos impedit voluptate quod at esse tenetur atque,
              architecto culpa doloribus minus iusto necessitatibus ipsum
              corrupti accusantium ab cumque accusamus! Quaerat, saepe.
            </p>
          </div>

          {/* services cards */}
          <div className="md:flex lg:flex gap-10 mx-auto">
            {/* card */}
            <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <div className=" bg-yellow-300 text-center shadow-sm p-5 rounded-xl my-10">
                <Image
                  src={graphicDesign}
                  alt="design image"
                  width={100}
                  height={100}
                  className="inline"
                />
                <h2 className="text-2xl font-bold">Graphic Designing</h2>
                <p className="text-sm py-2 text-gray-800 leading-6">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Nihil eius recusandae rerum voluptate, fugiat ex excepturi{" "}
                </p>
              </div>
            </motion.div>

            <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <div className=" bg-yellow-300 text-center shadow-sm p-5 rounded-xl my-10">
                <Image
                  src={code}
                  alt="design image"
                  width={100}
                  height={100}
                  className="inline"
                />
                <h2 className="text-2xl font-bold">Application Development</h2>
                <p className="text-sm py-2 text-gray-800 leading-6">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Nihil eius recusandae rerum voluptate, fugiat ex excepturi{" "}
                </p>
              </div>
            </motion.div>

            <motion.div whileHover={{ scale: 1.1 }} whileTap={{ scale: 0.9 }}>
              <div className=" bg-yellow-300 text-center shadow-sm p-5 rounded-xl my-10">
                <Image
                  src={graphicDesign}
                  alt="design image"
                  width={100}
                  height={100}
                  className="inline"
                />
                <h2 className="text-2xl font-bold">Web Development</h2>
                <p className="text-sm py-2 text-gray-800 leading-6">
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Nihil eius recusandae rerum voluptate, fugiat ex excepturi{" "}
                </p>
              </div>
            </motion.div>
          </div>
        </section>

        {/* My Work */}
        <section>
          <div>
            <h2 className="text-5xl py-10 font-bold opacity-60 dark:text-white">
              Portfolio
            </h2>
            <p className="text-sm py-2 text-gray-400 leading-6 dark:text-white">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Dignissimos impedit voluptate quod at esse tenetur atque,
              architecto culpa doloribus minus iusto necessitatibus ipsum
              corrupti accusantium ab cumque accusamus! Quaerat, saepe.
            </p>
          </div>

          {/* Images */}
          <div className="flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              >
                <Image
                  src={image1}
                  alt="image 1"
                  layout="responsive"
                  className="rounded-lg object-cover"
                />
              </motion.div>
            </div>
            <div className="basis-1/3 flex-1">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              >
                <Image
                  src={image2}
                  alt="image 1"
                  layout="responsive"
                  className="rounded-lg object-cover"
                />
              </motion.div>
            </div>
            <div className="basis-1/3 flex-1">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              >
                <Image
                  src={image1}
                  alt="image 1"
                  layout="responsive"
                  className="rounded-lg object-cover"
                />
              </motion.div>
            </div>
            <div className="basis-1/3 flex-1">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              >
                <Image
                  src={image3}
                  alt="image 1"
                  layout="responsive"
                  className="rounded-lg object-cover"
                />
              </motion.div>
            </div>
            <div className="basis-1/3 flex-1">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              >
                <Image
                  src={image1}
                  alt="image 1"
                  layout="responsive"
                  className="rounded-lg object-cover"
                />
              </motion.div>
            </div>
            <div className="basis-1/3 flex-1">
              <motion.div
                whileHover={{ scale: 1.1, rotate: 3 }}
                whileTap={{ scale: 0.8, rotate: -10, borderRadius: "100%" }}
              >
                <Image
                  src={image2}
                  alt="image 1"
                  layout="responsive"
                  className="rounded-lg object-cover"
                />
              </motion.div>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="border-t-2 border-black text-sm opacity-70 flex flex-col gap-5 items-center justify-center py-10 lg:flex-row lg:items-center dark:text-white dark:border-white">
          <div>
            <h3 className="text-base mb-2">Contact me for more details</h3>
            <p className="opacity-40">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Cupiditate est ea reiciendis magni architecto, minima neque modi
              amet a, maxime debitis eius ipsam ab voluptatibus? Commodi
              voluptas atque harum voluptatem?
            </p>
          </div>

          <div>
            <div className="flex text-5xl justify-center gap-16 text-gray-600">
              <a href="https://github.com/bklanuradha">
                <AiOutlineGithub />
              </a>
              <a href="https://www.linkedin.com/in/lakshmi-anuradha-53b679213/">
                <AiFillLinkedin />
              </a>
              <a href="https://www.instagram.com/anuradhakankanamge/">
                <AiOutlineInstagram />
              </a>
            </div>
          </div>
        </footer>
      </main>
    </div>
  );
}
